#!/usr/bin/env node
"use strict";

const fs = require("fs");
const path = require("path");

const ROOT = __dirname;
const DIST = path.join(ROOT, "dist");

const FILES_TO_COPY = [
  "style.css",
  "robots.txt",
  "sitemap.xml",
  "favicon.svg",
  "og-image.png",
];

function log(msg) {
  process.stdout.write(msg + "\n");
}

function buildScript() {

  const src = fs.readFileSync(path.join(ROOT, "script.js"), "utf8");
  fs.writeFileSync(path.join(DIST, "script.js"), src);
  log(`script.js copied readable: ${(src.length / 1024).toFixed(1)} KB (no obfuscation)`);
}

const CACHE_VERSION = 9;

function buildHtml() {
  let html = fs.readFileSync(path.join(ROOT, "index.html"), "utf8");

  html = html.replace(/(script\.js\?v=)\d+/g, `$1${CACHE_VERSION}`);
  html = html.replace(/(style\.css\?v=)\d+/g, `$1${CACHE_VERSION}`);
  fs.writeFileSync(path.join(DIST, "index.html"), html);
  log(`index.html copied (cache-busted to ?v=${CACHE_VERSION})`);
}

function writeVersionJson() {
  fs.writeFileSync(
    path.join(DIST, "version.json"),
    JSON.stringify({ built: new Date().toISOString(), version: CACHE_VERSION })
  );
  log("dist/version.json written");
}

function regenerateClassifier() {
  const src = fs.readFileSync(path.join(ROOT, "script.js"), "utf8");
  function skipString(s, i) {
    const q = s[i];
    if (q === '"' || q === "'") {
      i++;
      while (i < s.length) {
        if (s[i] === "\\") { i += 2; continue; }
        if (s[i] === q) return i + 1;
        i++;
      }
    } else if (q === "`") {
      i++;
      while (i < s.length) {
        if (s[i] === "\\") { i += 2; continue; }
        if (s[i] === "`") return i + 1;
        if (s[i] === "$" && s[i + 1] === "{") {
          let depth = 1; i += 2;
          while (i < s.length && depth) {
            const c = s[i];
            if (c === '"' || c === "'" || c === "`") { i = skipString(s, i); continue; }
            if (c === "{") depth++;
            else if (c === "}") depth--;
            i++;
          }
          continue;
        }
        i++;
      }
    }
    return i;
  }
  function extractBalanced(s, fromMark, open, close) {
    const start = s.indexOf(fromMark);
    if (start < 0) throw new Error("classifier marker not found: " + fromMark);
    let i = start, depth = 0;
    while (i < s.length) {
      const c = s[i];
      if (c === '"' || c === "'" || c === "`") { i = skipString(s, i); continue; }
      if (c === "/" && (s[i + 1] === "/" || s[i + 1] === "*")) {
        if (s[i + 1] === "/") { const e = s.indexOf("\n", i); i = e < 0 ? s.length : e + 1; }
        else { const e = s.indexOf("*/", i + 2); i = e < 0 ? s.length : e + 2; }
        continue;
      }
      if (c === open) depth++;
      else if (c === close) { depth--; if (depth === 0) return s.slice(start, i + 1); }
      i++;
    }
    throw new Error("unbalanced classifier block: " + fromMark);
  }
  const fn = (name) => extractBalanced(src, "function " + name + "(", "{", "}");
  const constLine = (name) => {
    const re = new RegExp("const " + name + " = [^\\n]*;");
    const m = src.match(re);
    if (!m) throw new Error("classifier const not found: " + name);
    return m[0];
  };
  const body = [
    extractBalanced(src, "const IDEOLOGIES = [", "[", "]"),
    extractBalanced(src, "const SIG = {", "{", "}"),
    extractBalanced(src, "const PREFS = {", "{", "}"),
    extractBalanced(src, "const PREF_SCALE = {", "{", "}"),
    extractBalanced(src, "const GOVT_LABELS = {", "{", "}"),
    extractBalanced(src, "const ZONE_BLURB = {", "{", "}"),
    fn("clampCompass"), fn("clampCensus"), fn("compassPoint"),
    fn("sigValue"), fn("sigPass"), fn("prefsScore"), fn("prefsReason"),
    constLine("tradAdj"), constLine("RAD_CEIL"), constLine("radPct"), constLine("radAdj"), constLine("humanJoin"),
    fn("compassTerritory"), fn("sigFailReason"), fn("ideoExplanation"), fn("specificIdeology")
  ].join("\n");
  const out = `// GENERATED FILE — do not edit by hand (regenerated by build.cjs from script.js).
"use strict";

${body}
module.exports = { specificIdeology, compassPoint, IDEOLOGIES, sigPass, prefsScore };
`;
  fs.writeFileSync(path.join(ROOT, "api", "_classifier.cjs"), out);
  log("api/_classifier.cjs regenerated");
}

fs.mkdirSync(DIST, { recursive: true });
try {
  regenerateClassifier();
} catch (err) {

  log("WARNING: could not regenerate api/_classifier.cjs: " + err.message);
}
for (const f of FILES_TO_COPY) {
  fs.copyFileSync(path.join(ROOT, f), path.join(DIST, f));
  log(`copied ${f}`);
}
buildScript();
buildHtml();
writeVersionJson();
log("build complete: dist/ ready");
