// GENERATED FILE — do not edit by hand (regenerated by build.cjs from script.js).
"use strict";

const IDEOLOGIES = [

    ["Anarcho-Capitalism", "Libertarian Right", 88, 74, 46, 55, "Stateless capitalism: every service privately provided, purely voluntary association."],
    ["Libertarianism", "Libertarian Right", 56, 62, 32, 38, "Free markets and strong individual rights under a minimal state."],
    ["Minarchism", "Libertarian Right", 76, 44, 48, 44, "Night-watchman state limited to courts, police and defence."],
    ["Paleolibertarianism", "Libertarian Right", 70, 0, 84, 60, "Radical free markets wedded to traditionalist social values."],
    ["Classical Liberalism", "Libertarian Right", 48, 40, 34, 32, "Free markets and civil liberties under a limited constitutional government."],
    ["Social Liberalism", "Centre-Right", 30, 36, 22, 30, "Free-market economy with strong civil liberties, strict laicity and equal opportunity."],
    ["Fiscal Conservatism", "Centre-Right", 32, 18, 56, 34, "Low taxation and a small public sector: the state takes a minimal share of output and spends little on redistribution."],
    ["Neoconservatism", "Centre-Right", 46, -14, 62, 62, "Free-market economics with strong defence spending and a patriotic, traditionalist society."],

    ["Anarcho-Communism", "Libertarian Left", -90, 82, 26, 88, "Stateless, classless, common ownership: 'from each according to ability, to each according to need'."],
    ["Anarcho-Syndicalism", "Libertarian Left", -58, 86, 30, 74, "Worker-run industry in a near-stateless society: collective ownership of production under maximal civil liberties."],
    ["Anarcho-Pacifism", "Libertarian Left", -20, 86, 26, 60, "Stateless and antimilitarist; change comes only through non-violence and free cooperation."],
    ["Anarcho-Primitivism", "Libertarian Left", -86, 56, 44, 95, "Dismantle industrial civilisation and settled agriculture; return to tribal hunter-gatherer life."],
    ["Libertarian Socialism", "Libertarian Left", -66, 66, 30, 70, "Broad civil liberties with worker self-management: collective ownership without an authoritarian state apparatus."],
    ["Mutualism", "Libertarian Left", -42, 52, 44, 46, "Free association of producers; mutual credit banks, no rent or profit."],
    ["Council Communism", "Libertarian Left", -86, 74, 14, 86, "Direct democracy through workers' councils: far-left ownership with maximal political participation and civil liberties."],
    ["Luxemburgism", "Libertarian Left", -60, 66, 14, 80, "Revolutionary socialism with genuine mass participation: far-left economics, high civil liberties and a highly politicised society."],
    ["Communalism", "Libertarian Left", -48, 62, 16, 60, "Confederal, ecological democracy of local assemblies; a green libertarian municipalism."],
    ["Participatory Socialism", "Democratic Left", -78, 46, 16, 44, "Society-wide public ownership run through citizen assemblies, co-ops and democratic planning."],
    ["Market Socialism", "Democratic Left", -35, 37, 24, 37, "Worker-owned cooperatives competing in markets: collective ownership of industry combined with genuine market exchange and political liberty."],

    ["Centrism", "Centrist", 4, 2, 46, 12, "Pragmatic middle: mixed markets, moderate welfare, steady reform."],
    ["Solidarism", "Centrist", 8, 6, 70, 20, "Society organised around solidarity, interclass cooperation and universal social insurance."],
    ["Distributism", "Centre", -8, -14, 78, 30, "Property spread widely: small owners, craftsmen and cooperatives over state or monopoly capital."],
    ["Ecomodernism", "Centre-Right", 21, 20, 28, 37, "High-technology environmentalism: strong eco-friendliness and scientific advancement paired with a substantial industrial base."],
    ["Ordoliberalism", "Centre-Right", 24, 4, 48, 22, "Free markets framed by strict state rules against monopoly and inflation."],
    ["Peronism", "Centre", -14, -16, 62, 58, "Justicialism: social justice, economic independence, sovereignty; interclassist and pragmatic."],

    ["Social Democracy", "Centre-Left", -16, 14, 34, 22, "Regulated capitalism with a strong welfare state, unions and redistribution."],
    ["Fabian Socialism", "Centre-Left", -30, 8, 46, 24, "The gradual, parliamentary, bureaucratic road to socialism."],
    ["Democratic Socialism", "Centre-Left", -54, 22, 36, 36, "Social ownership of the commanding heights, pursued democratically."],
    ["Eco-Socialism", "Centre-Left", -24, 38, 42, 54, "Green transition achieved through social ownership and planning."],
    ["Degrowth", "Centre-Left", -36, 24, 46, 58, "Deliberately low per-capita income combined with strong environmental protection: production is voluntarily constrained within ecological limits."],
    ["Eurocommunism", "Centre-Left", -50, -2, 42, 42, "Communist parties that accept parliamentary democracy, pluralism and civil rights."],
    ["Jacobinism", "Centre-Left", -44, 8, 50, 78, "Radical republicanism: a highly politicised, mobilised citizenry under a strong central state."],
    ["Religious Socialism", "Centre-Left", -26, 12, 72, 28, "Faith-inspired social ownership and welfare; religious tradition behind redistribution."],
    ["Left-Wing Populism", "Centre-Left", -34, -14, 60, 66, "Redistribution-led majoritarian politics: high welfare and equality with an activist, mobilised electorate."],

    ["One-Nation Conservatism", "Centre-Right", 6, -16, 72, 30, "Free markets tempered by social cohesion, tradition and a welfare floor."],
    ["Paleoconservatism", "Authoritarian Right", 14, -24, 97, 58, "Traditionalist and localist: near-maximal social conservatism and religiosity with strong patriotism."],
    ["National Conservatism", "Authoritarian Right", 26, -30, 88, 52, "Tradition, national identity and sovereignty over multicultural globalism."],
    ["Religious Nationalism", "Authoritarian Right", 18, -42, 96, 64, "National identity fused with militant religious tradition against secularism."],
    ["Religious Democracy", "Centre-Right", -12, -26, 82, 26, "Market economy restrained by faith-inspired social solidarity and subsidiarity."],
    ["Right-Wing Populism", "Authoritarian Right", 30, -2, 84, 68, "Majoritarian nationalism: a mobilised, patriotic and socially conservative society under a constrained liberal order."],
    ["Timocracy", "Centre-Right", 30, -22, 60, 42, "Political rights concentrated among property and military elites: pronounced wealth gaps alongside a substantial defence establishment."],

    ["Authoritarianism", "Authoritarian", 4, -44, 62, 44, "Concentrated executive power with little tolerance for dissent."],
    ["Technocracy", "Authoritarian", 14, -36, 28, 38, "Rule by technical expertise: an exceptionally educated and intelligent society governed through a large administrative apparatus."],
    ["Constitutional Monarchism", "Authoritarian", 0, -52, 90, 42, "A constitutional monarchy: the game classifies the state as a monarchy constrained by democratic institutions, in a deeply traditional society."],
    ["Absolute Monarchism", "Authoritarian", -4, -70, 97, 52, "An absolute monarchy: the game classifies the state as an unconstrained hereditary monarchy, in a deeply traditional society."],
    ["Theocracy", "Authoritarian", -10, -66, 98, 70, "Religious law is the law of the land."],
    ["Authoritarian Socialism", "Authoritarian Left", -52, -38, 58, 76, "Command economy under strict, single-party control of society."],
    ["Communism", "Authoritarian Left", -76, -64, 62, 90, "Totalising state socialism organised by a vanguard party."],
    ["Stalinism", "Authoritarian Left", -62, -72, 66, 98, "Rigid five-year-plan command economy; single-party terror against dissent."],
    ["Maoism", "Authoritarian Left", -56, -58, 74, 99, "A peasant-based revolutionary state: an agrarian economy under a highly mobilised, politicised society with extreme radicality."],
    ["Trotskyism", "Authoritarian Left", -84, -18, 30, 94, "Revolutionary far-left politics under libertarian conditions: maximal radicality with strong civil liberties and a participatory state."],
    ["State Atheism", "Authoritarian Left", -68, -50, 14, 92, "Officially atheist vanguard state that confines religion to private life."],
    ["Juche", "Authoritarian Left", -54, -78, 80, 94, "Autarkic, ultra-nationalist state socialism centred on the leader."],
    ["Authoritarian Capitalism", "Authoritarian Right", 56, -52, 58, 62, "Markets kept, but civil liberties and political opposition curtailed."],
    ["Plutocracy", "Authoritarian Right", 50, -42, 36, 50, "Wealth rules: extreme concentration of riches alongside heavy business subsidisation and a curtailed political arena."],
    ["State Capitalism", "Authoritarian", 38, -32, 46, 52, "Big state-owned conglomerates competing on capitalist terms (Chinese model)."],
    ["Fascism", "Authoritarian Right", 76, -68, 80, 92, "Everything within the state: aggressive nationalism, corporatism, leader cult."],
    ["Clerical Fascism", "Authoritarian Right", 38, -62, 96, 90, "Fascist mobilisation fused with intransigent religious integralism."],
    ["Neo-Fascism", "Authoritarian Right", 60, -80, 74, 96, "Ethno-nationalist, anti-capitalist authoritarianism rejecting both blocs."],
    ["Nazism", "Authoritarian Right", 86, -84, 62, 99, "Biological supremacist totalitarianism; state, race and empire fused."]
  ]
const SIG = {

    "Anarcho-Primitivism": [
      { rank: { 69: { min: 60 } } },
      { rank: { 7: { min: 55 }, 70: { max: 45 } } }
    ],

    "Theocracy": [
      { rank: { 32: { min: 55 } } },
      { govt: { spirituality: { min: 20 } } }
    ],
    "Clerical Fascism": [
      { rank: { 32: { min: 55 } } },
      { govt: { spirituality: { min: 20 } } }
    ],

    "Juche": [{ rank: { 32: { max: 55 } } }],
    "State Atheism": [{ rank: { 32: { max: 40 } } }],

    "Anarcho-Pacifism": [{ rank: { 47: { min: 50 } } }],

    "Fascism": [{ rank: { 53: { min: 50 } } }, { rank: { 46: { min: 50 } } }, { rank: { 59: { min: 50 } } }],
    "Neo-Fascism": [{ rank: { 53: { min: 55 } } }, { rank: { 46: { min: 55 } } }, { rank: { 59: { min: 55 } } }],
    "Nazism": [{ rank: { 53: { min: 55 } } }, { rank: { 59: { min: 60 } } }],

    "Constitutional Monarchism": [{ category: { in: ["Constitutional Monarchy", "Absolute Monarchy"] } }],
    "Absolute Monarchism": [{ category: { in: ["Absolute Monarchy"] } }],

    "Technocracy": [{ rank: { 36: { min: 60 } } }],

    "Anarcho-Capitalism": [{ score: { 49: { max: 30 } } }],
    "Minarchism": [{ score: { 49: { max: 45 } } }],
    "Libertarianism": [{ score: { 49: { max: 65 } } }],
    "Classical Liberalism": [{ score: { 49: { max: 75 } } }]
  }
const PREFS = {
    "Social Democracy": { rank: { 28: { min: 45 }, 29: { min: 45 }, 75: { min: 40 } }, govt: { welfare: { min: 12 }, healthcare: { min: 8 } } },
    "Religious Socialism": { rank: { 28: { min: 40 }, 32: { min: 35 } } },
    "Democratic Socialism": { rank: { 28: { min: 40 }, 33: { min: 45 } } },
    "Fabian Socialism": { rank: { 29: { min: 45 }, 75: { min: 45 } } },
    "Participatory Socialism": { rank: { 33: { min: 40 }, 7: { min: 35 } } },
    "Market Socialism": { rank: { 48: { min: 55 } } },
    "Eco-Socialism": { rank: { 7: { min: 55 } }, govt: { environment: { min: 6 } } },
    "Communalism": { rank: { 7: { min: 50 } } },
    "Ecomodernism": { rank: { 7: { min: 55 }, 70: { min: 55 } }, govt: { environment: { min: 5 } } },
    "Degrowth": { rank: { 7: { min: 45 }, 72: { max: 50 } }, govt: { environment: { min: 6 } } },
    "Anarcho-Communism": { rank: { 33: { min: 50 } } },
    "Anarcho-Capitalism": { rank: { 48: { min: 60 } } },
    "Libertarianism": { rank: { 48: { min: 50 } } },
    "Classical Liberalism": { rank: { 48: { min: 55 }, 62: { min: 40 } } },
    "Social Liberalism": { rank: { 62: { min: 45 } } },
    "Authoritarianism": { rank: { 53: { min: 60 } } },
    "State Capitalism": { rank: { 27: { min: 55 } }, govt: { administration: { min: 12 } } },
    "Religious Democracy": { rank: { 32: { min: 45 } } },
    "Paleoconservatism": { rank: { 8: { min: 60 }, 32: { min: 45 } } },
    "National Conservatism": { rank: { 8: { min: 55 }, 87: { min: 45 } } },
    "Fiscal Conservatism": { rank: { 49: { max: 45 } }, govt: { administration: { max: 8 }, welfare: { max: 8 } } },
    "Neoconservatism": { rank: { 87: { min: 55 } }, govt: { defence: { min: 12 } } },
    "Technocracy": { rank: { 36: { min: 55 } }, govt: { administration: { min: 8 } } },
    "Maoism": { rank: { 17: { min: 55 }, 38: { min: 55 } } },
    "Jacobinism": { rank: { 38: { min: 55 }, 54: { min: 40 } } },
    "Left-Wing Populism": { rank: { 38: { min: 50 }, 28: { min: 45 } } },
    "Right-Wing Populism": { rank: { 38: { min: 50 }, 87: { min: 55 } } },
    "Luxemburgism": { rank: { 38: { min: 45 }, 45: { min: 70 } } },
    "Trotskyism": { rank: { 38: { min: 45 }, 54: { min: 40 } } },
    "Plutocracy": { rank: { 74: { min: 60 } }, govt: { commerce: { min: 10 } } }
  }
const PREF_SCALE = { 1: "economic output", 7: "eco-friendliness", 8: "social conservatism", 17: "agriculture sector", 27: "government size",
    28: "welfare", 29: "public healthcare", 32: "religiousness", 33: "income equality", 36: "intelligence", 38: "political apathy (inverted)",
    42: "compliance", 43: "safety", 45: "ideological radicality", 46: "defence spending", 47: "pacifism", 48: "economic freedom",
    49: "taxation", 53: "authoritarianism", 54: "youth rebelliousness", 59: "weaponization", 62: "secularism",
    69: "primitiveness", 70: "scientific advancement", 72: "average income (per capita)", 75: "public education", 87: "patriotism" }
const GOVT_LABELS = { administration: "Administration", defence: "Defence", education: "Education", environment: "Environment", healthcare: "Healthcare", commerce: "Commerce", spirituality: "Spirituality", welfare: "Welfare", lawandorder: "Law & Order", social: "Social Equality", transport: "Public Transport", aid: "International Aid" }
const ZONE_BLURB = {
    "authoritarian,left": "a state-run economy under concentrated power",
    "authoritarian,center": "concentrated power without a strong economic lean",
    "authoritarian,right": "markets or private wealth under concentrated power",
    "centrist,left": "a mixed economy with a moderate state",
    "centrist,center": "the pragmatic middle — balanced economy and freedoms",
    "centrist,right": "a mostly private economy with a moderate state",
    "libertarian,left": "wide civil liberties on a collectively-run economy",
    "libertarian,center": "wide personal freedoms with a balanced economy",
    "libertarian,right": "wide civil liberties on a free-market economy"
  }
function clampCompass(v) { return Math.max(-100, Math.min(100, v)); }
function clampCensus(v, fb = null) {
    return Number.isFinite(v) ? Math.max(0, Math.min(100, v)) : fb;
  }
function compassPoint(scales, extras) {
    const byId = Object.fromEntries(scales.map((s) => [s.id, s]));
    const civil = clampCensus(byId[0]?.score, 50);
    const econ = clampCensus(byId[1]?.score, 50);
    const pol = clampCensus(byId[2]?.score, 50);
    const govtSize = byId[27] ? clampCensus(byId[27].score) : null;

    const efRaw = byId[48] && Number.isFinite(byId[48].score) ? Math.max(-100, Math.min(100, byId[48].score)) : null;
    const econFree = efRaw != null ? (efRaw + 100) / 2 : null;

    const entityType = (extras && extras.entityType) || "nation";

    const rank = {};
    const scores = {};
    scales.forEach((s) => {
      if (Number.isFinite(s.score)) scores[s.id] = s.score;
      if (Number.isFinite(s.prank)) rank[s.id] = Math.max(0, Math.min(100, 100 - s.prank));
    });

    let x = (econ - 50) * 2;
    let y = ((civil + pol) / 2 - 50) * 2;

    let lean = null;
    if (extras && extras.sectors) {
      const s = extras.sectors;
      const marketShare = (s.private || 0) + (s.black || 0);
      const stateShare = (s.state || 0);
      const total = marketShare + stateShare;
      if (total > 0) lean = (marketShare - stateShare) / total;
    } else if (Number.isFinite(econFree)) {
      lean = Math.max(-1, Math.min(1, (econFree - 50) / 50));
    }
    if (lean !== null) {

      const idx = Number.isFinite(econFree) ? (econFree + econ) / 2 : econ;

      const blend = Math.abs(lean) > 0.25 ? 0.9 : 0.45;
      x = lean * 92 * blend + (idx - 50) * (1 - blend);
    }

    const welfareRank = Number.isFinite(rank[28]) ? rank[28] : null;
    const taxIn = Number.isFinite(extras && extras.tax) ? Math.max(0, Math.min(100, extras.tax)) : null;
    const redistParts = [];
    if (welfareRank != null) redistParts.push((50 - welfareRank) * 0.2);
    if (taxIn != null) redistParts.push((50 - taxIn) * 0.3);
    if (redistParts.length) {
      const redist = redistParts.reduce((a, b) => a + b, 0) / redistParts.length;
      x += Math.max(-15, Math.min(15, redist));
    }

    if (Number.isFinite(govtSize)) y -= (govtSize - 50) * 0.6;

    const sec = (id) => { const s = byId[id]; return Number.isFinite(s?.score) ? clampCensus(s.score) : null; };

    let govt = null;
    if (extras && extras.govt && typeof extras.govt === "object") {
      govt = {};
      for (const k of Object.keys(extras.govt)) {
        const v = Number(extras.govt[k]);
        if (Number.isFinite(v)) govt[k] = Math.max(0, Math.min(100, v));
      }
    }
    const category = extras && typeof extras.category === "string" ? extras.category.trim() : null;

    return {
      x: clampCompass(x),
      y: clampCompass(y),
      civil, econ, pol, govtSize, entityType,
      rank, scores, govt, category, tax: taxIn, welfareRank,

      progressive: (civil + pol) / 2,

      socCons: sec(8),
      relig: entityType === "nation" ? (rank[32] != null ? rank[32] : sec(32)) : null,
      radical: sec(45),
      secular: sec(62),
      econFree,
      econFreeRaw: efRaw
    };
  }
function sigValue(p, kind, id) {
    if (kind === "rank") return (p.rank && Number.isFinite(p.rank[id]) ? p.rank[id] : null);
    if (kind === "govt") { const g = p.govt; return (g && Number.isFinite(g[id]) ? g[id] : null); }
    if (kind === "category") return (typeof p.category === "string" ? p.category : null);
    return (p.scores && Number.isFinite(p.scores[id]) ? p.scores[id] : null);
  }
function sigPass(name, p) {
    const alts = SIG[name];
    if (!alts || !alts.length) return true;

    let anyEvaluated = false;
    for (const alt of alts) {
      let ok = true, anyData = false;
      for (const kind of Object.keys(alt)) {

        if (kind === "category") {
          const v = sigValue(p, "category", null);
          if (v == null) continue;
          anyData = true;
          if (alt[kind].in && !alt[kind].in.includes(v)) { ok = false; break; }
          continue;
        }
        for (const idStr of Object.keys(alt[kind])) {
          const v = sigValue(p, kind, idStr);
          if (v == null) continue;
          anyData = true;
          const cond = alt[kind][idStr];
          if ((cond.min != null && v < cond.min) || (cond.max != null && v > cond.max)) { ok = false; break; }
        }
        if (!ok) break;
      }
      if (anyData) anyEvaluated = true;
      if (ok && anyData) return true;
    }
    return anyEvaluated ? false : true;
  }
function prefsScore(name, p) {
    const rules = PREFS[name];
    if (!rules) return -1;
    let ok = 0, n = 0;
    for (const kind of ["rank", "govt"]) {
      const m = rules[kind];
      if (!m) continue;
      for (const idStr of Object.keys(m)) {
        const v = sigValue(p, kind, idStr);
        if (v == null) continue;
        n++;
        const cond = m[idStr];
        if ((cond.min == null || v >= cond.min) && (cond.max == null || v <= cond.max)) ok++;
      }
    }
    return n ? ok / n : -1;
  }
function prefsReason(name, p) {
    const rules = PREFS[name];
    const hits = [];
    if (rules) {
      for (const kind of ["rank", "govt"]) {
        const m = rules[kind];
        if (!m) continue;
        for (const idStr of Object.keys(m)) {
          const v = sigValue(p, kind, idStr);
          if (v == null) continue;
          const cond = m[idStr];
          if ((cond.min == null || v >= cond.min) && (cond.max == null || v <= cond.max)) {
            const label = kind === "govt"
              ? (GOVT_LABELS[idStr] || idStr) + " budget"
              : (PREF_SCALE[Number(idStr)] || `scale ${idStr}`);
            hits.push(`${label} (${Math.round(v)}${kind === "govt" ? "%" : "/100"})`);
          }
        }
      }
    }
    return hits.slice(0, 3).join(", ");
  }
const tradAdj = (t) => t >= 70 ? "highly traditional" : t >= 55 ? "traditional-leaning" : t >= 40 ? "moderately traditional" : t >= 25 ? "moderately secular" : "strongly secular";
const RAD_CEIL = 51;
const radPct = (r) => (Number.isFinite(r) ? Math.max(0, Math.min(100, (r / RAD_CEIL) * 100)) : null);
const radAdj = (r) => { const q = radPct(r); return q == null ? "" : q >= 75 ? "highly radical" : q >= 55 ? "markedly radical" : q >= 35 ? "moderately radical" : q >= 20 ? "mildly radical" : "of low radicality"; };
const humanJoin = (a) => { if (!a || !a.length) return ""; if (a.length === 1) return a[0]; if (a.length === 2) return `${a[0]} and ${a[1]}`; return a.slice(0, -1).join(", ") + " and " + a[a.length - 1]; };
function compassTerritory(p) {
    const xz = p.x < -33 ? "left" : p.x > 33 ? "right" : "center";
    const yz = p.y < -33 ? "authoritarian" : p.y > 33 ? "libertarian" : "centrist";
    const names = {
      "authoritarian,left": "Authoritarian Left", "authoritarian,center": "Authoritarian", "authoritarian,right": "Authoritarian Right",
      "centrist,left": "Centre-Left", "centrist,center": "Centrist", "centrist,right": "Centre-Right",
      "libertarian,left": "Libertarian Left", "libertarian,center": "Libertarian", "libertarian,right": "Libertarian Right"
    };
    return { key: `${yz},${xz}`, name: names[`${yz},${xz}`] };
  }
function sigFailReason(p, name) {
    const r = (id) => (Number.isFinite(p.rank?.[id]) ? p.rank[id] : null);
    if (name === "Anarcho-Primitivism") {
      const prim = r(69), tech = r(70);
      const bits = [];
      if (prim != null) bits.push(`Primitiveness intensity ${prim}/100 — among the world's least primitive`);
      if (tech != null) bits.push(`Scientific Advancement intensity ${tech}/100`);
      return "the census shows a highly civilised, industrial society (" + (bits.join("; ") || "low primitiveness") + ")";
    }
    if (name === "Theocracy" || name === "Clerical Fascism") {
      const rl = r(32);
      return rl != null ? `religiousness is only intensity ${rl}/100 in the census` : "the census shows a secular society";
    }
    if (name === "Juche" || name === "State Atheism") {
      const rl = r(32);
      return rl != null ? `the census shows a devout society (Religiousness intensity ${rl}/100, incompatible with official state atheism)` : "its census contradicts official atheism";
    }
    if (name === "Anarcho-Pacifism") {
      const pac = r(47);
      return pac != null ? `its census shows a militarised society (Pacifism intensity ${pac}/100)` : "its census contradicts pacifism";
    }
    if (name === "Fascism" || name === "Neo-Fascism" || name === "Nazism") {
      const a = r(53), w = r(59), de = r(46);
      const vals = [a != null ? `authoritarianism ${a}` : null, w != null ? `weaponization ${w}` : null, de != null ? `defence ${de}` : null].filter(Boolean).join(", ");
      return "its census shows no real militarist-authoritarian machinery (" + (vals || "intensities all low") + " /100)";
    }
    if (name === "Technocracy") {
      const iq = r(36);
      return iq != null ? `the society's measured Intelligence intensity is only ${iq}/100 — not an expert class` : "its census contradicts rule by expertise";
    }
    if (name === "Anarcho-Capitalism" || name === "Minarchism" || name === "Libertarianism" || name === "Classical Liberalism") {
      const t = p.scores && Number.isFinite(p.scores[49]) ? Math.round(p.scores[49]) : null;
      return t != null
        ? `the state levies a ${t}% tax rate${t > 70 ? " — a confiscatory burden incompatible with a stateless or minimal-state economy" : " — beyond what the label's limited state admits"}`
        : "its taxation profile contradicts the label";
    }
    if (name === "Constitutional Monarchism" || name === "Absolute Monarchism") {
      return p.category ? `the game category is \u201c${p.category}\u201d, not a monarchy` : "the form of the head of state cannot be confirmed";
    }
    return "its census profile contradicts the label";
  }
function ideoExplanation(winner, vetoes, rivals, p, econWord, freeWord, govtSpending, policies, mapLeader, f) {
    const R = (n) => (Number.isFinite(n) ? Math.round(n) : null);
    const zone = compassTerritory(p);
    const P = [];

    let lead = `Closest of the ${IDEOLOGIES.length} named ideologies: ${winner.name} (${winner.family}). ${winner.note} The entity is positioned in the ${zone.name} zone (X ${R(f.x)}, Y ${R(f.y)}), which corresponds to ${ZONE_BLURB[zone.key] || zone.name}. `;
    if (f.mktPct != null) {
      lead += `The economic axis is derived from the production split (${R(f.mktPct)}% private or black-market, ${R(100 - f.mktPct)}% state-owned${Number.isFinite(f.econFree) ? `; Economic Freedom scores ${R(f.econFree)}/100 on the same market-state spectrum` : ""}). `;
    } else if (Number.isFinite(f.econFree)) {
      lead += `The economic axis is derived from the Economic Freedom census, which scores ${R(f.econFree)}/100. `;
    } else if (Number.isFinite(f.econ)) {
      lead += `The economic axis is derived from the Economy index (${R(f.econ)}/100). `;
    } else {
      lead += `The economic reading is consistent with the position. `;
    }
    if (Number.isFinite(f.civil) && Number.isFinite(f.pol)) {
      lead += `The authority axis is derived from Civil Rights (${R(f.civil)}) and Political Freedom (${R(f.pol)}), whose mean is ${R((f.civil + f.pol) / 2)}`;
      if (Number.isFinite(f.govtSize)) {
        const nudge = (f.govtSize - 50) * 0.6;
        if (Math.abs(nudge) >= 1) {
          lead += `, adjusted for Government Size (${R(f.govtSize)}/100, ${nudge > 0 ? "an authoritarian" : "a libertarian"} shift of about ${R(Math.abs(nudge))} points)`;
        }
      }
      lead += `. Together they describe an economy that is ${econWord} and a civil-liberties regime that is ${freeWord}, the defining combination of ${winner.name}.`;
    } else {
      lead += `The regime is ${econWord} economically with ${freeWord} civil liberties, the defining combination of ${winner.name}.`;
    }
    if (Number.isFinite(f.tax) || Number.isFinite(f.welfareRank)) {
      const parts = [];
      if (Number.isFinite(f.tax)) parts.push(`a tax rate of ${R(f.tax)}%`);
      if (Number.isFinite(f.welfareRank)) parts.push(`welfare spending at the ${R(f.welfareRank)}th world percentile`);
      const hiTax = Number.isFinite(f.tax) && f.tax > 50;
      const hiWel = Number.isFinite(f.welfareRank) && f.welfareRank > 50;
      const dir = hiTax || hiWel ? "leftward" : "rightward";
      lead += ` The redistribution evidence — ${humanJoin(parts)} — shifts the economic axis ${dir}.`;
    }
    P.push(lead);

    let soc = `The society factors used in the classification are consistent with the label. Traditionalism is ${R(f.trad)}/100 (${tradAdj(f.trad)}), based on ${f.socBits && f.socBits.length ? humanJoin(f.socBits) : "an estimate from the level of civil liberty; no society scales were available"}`;
    if (f.radic != null) soc += `; radicality is ${R(f.radic)} on the census's 0-100 scale (${radAdj(f.radic)} — the census rarely exceeds ~51, where ${R(f.radic)} sits at ${R(radPct(f.radic))}% of the observed maximum), from Ideological Radicality`;
    soc += `. The distance from the entity to the label's anchor — X ${R(f.cx)}, Y ${R(f.cy)}, traditionalism ${R(f.tExp)}, radicality ${R(f.rExp)} — is ${R(f.dist)} points in the four-dimensional space used by the classifier.`;
    P.push(soc);

    let why = null;
    if (vetoes.length) {
      const v0 = vetoes[0];
      why = `${v0.name} is the nearest ideology by map distance, but it requires a definitional census signature that is not met (${sigFailReason(p, v0.name)}). Labels contradicted by the census are excluded from consideration; the classification therefore falls to ${winner.name}, the closest ideology whose signature is satisfied.`;
    } else if (mapLeader && winner !== mapLeader) {
      const r = prefsReason(winner.name, p);
      why = `${mapLeader.name} is marginally closer in map distance. Its census profile, however, does not fit the entity${r ? `, whereas the defining traits of ${winner.name} are present (${r})` : ""}. When two labels are nearly equidistant, the census profile is used to decide between them; in this case it selects ${winner.name}.`;
    } else if (rivals.length) {
      const rr = rivals[0];
      if (f.dec) {
        why = `The closest rival is ${rr.name}. The two anchors differ most on ${f.dec.dim}: the entity measures ${R(f.dec.v)}, which is nearer to ${winner.name}'s anchor (${R(f.dec.ew)}) than to ${rr.name}'s (${R(f.dec.er)}). On the remaining dimensions the two labels are comparable, so this dimension determines the choice.`;
      } else {
        why = `The closest rival, ${rr.name}, is farther on every measured dimension and is not selected.`;
      }
    }
    if (why) P.push(why);

    const tail = [];
    if (f.corr) tail.push(`The entity's world percentile ranks corroborate the label: ${f.corr}.`);
    if (f.gap) tail.push(`The classification is not exact — the largest deviation from the anchor is on ${f.gap.dim} (${R(f.gap.v)} points) — but no other ideology reconciles all measured dimensions better.`);
    if (govtSpending && govtSpending.length) {
      const sorted = govtSpending.slice().sort((a, b) => b.value - a.value);
      tail.push(`Budget priorities are consistent with the label: ${sorted[0].label.toLowerCase()} (${sorted[0].value.toFixed(1)}%)${sorted[1] ? `, ${sorted[1].label.toLowerCase()} (${sorted[1].value.toFixed(1)}%)` : ""}${sorted[2] ? ` and ${sorted[2].label.toLowerCase()} (${sorted[2].value.toFixed(1)}%)` : ""} of spending.`);
    }
    if (policies && policies.length) {
      tail.push(`Enshrined policies: ${policies.slice(0, 4).join(", ")}${policies.length > 4 ? ", among others" : ""}.`);
    }
    if (tail.length) P.push(tail.join(" "));

    return P.join("\n\n");
  }
function specificIdeology(p, govtSpending, sectors, policies) {
    const pol = p.pol, econ = p.econ;
    const x = p.x, y = p.y;

    let trad;
    const tradParts = [];
    if (Number.isFinite(p.socCons)) tradParts.push(p.socCons);
    if (Number.isFinite(p.relig)) tradParts.push(p.relig);
    if (tradParts.length) trad = tradParts.reduce((a, b) => a + b, 0) / tradParts.length;
    else trad = 100 - (p.progressive ?? 50);
    trad = Math.max(0, Math.min(100, trad));

    const radic = Number.isFinite(p.radical) ? Math.max(0, Math.min(100, (p.radical / 51) * 100)) : null;

    let econWord;
    if (sectors && Number.isFinite(sectors.state) && Number.isFinite(sectors.private)) {
      const marketSH = (sectors.private || 0) + (sectors.black || 0);
      const stateSH = sectors.state || 0;
      const marketPct = marketSH + stateSH > 0 ? marketSH / (marketSH + stateSH) : 0.5;
      econWord = marketPct >= 0.66 ? "laissez-faire" : marketPct >= 0.4 ? "mixed-market" : "state-planned";
    } else if (Number.isFinite(p.econFree)) {
      econWord = p.econFree >= 66 ? "laissez-faire" : p.econFree >= 40 ? "mixed-market" : "planned";
    } else {
      econWord = econ >= 66 ? "laissez-faire" : econ >= 40 ? "mixed-market" : "planned";
    }
    const freeWord = pol >= 66 ? "liberal" : pol >= 40 ? "moderate" : "restrictive";

    const KT = 0.6, KR = 0.45;
    const scored = IDEOLOGIES.map(([name, family, cx, cy, tExp, rExp, note]) => {
      const dx = x - cx, dy = y - cy, dt = (trad - tExp) * KT;
      const dr = radic == null ? 0 : (radic - rExp) * KR;
      return { name, family, note, tExp, d: Math.sqrt(dx * dx + dy * dy + dt * dt + dr * dr) };
    }).sort((a, b) => a.d - b.d);

    const vetoes = [];
    for (const cand of scored) {
      if (sigPass(cand.name, p)) break;
      vetoes.push(cand);
    }
    const passable = scored.filter((c) => sigPass(c.name, p));
    if (!passable.length) passable.push(scored[0]);

    const band = passable.filter((c) => c.d <= passable[0].d + 5);
    const PROF_BONUS = 6;
    const mapLeader = band[0];
    let winner = mapLeader;
    let bestEff = winner.d - Math.max(0, prefsScore(winner.name, p)) * PROF_BONUS;
    for (let i = 1; i < band.length; i++) {
      const f = prefsScore(band[i].name, p);
      const eff = f < 0 ? band[i].d : band[i].d - PROF_BONUS * f;
      if (eff < bestEff) { bestEff = eff; winner = band[i]; }
    }
    const rivals = passable.filter((c) => c !== winner).slice(0, 2);

    const rowOf = (nm) => IDEOLOGIES.find((r) => r[0] === nm);
    const wRow = rowOf(winner.name);

    let mktPct = null;
    if (sectors && Number.isFinite(sectors.state) && Number.isFinite(sectors.private)) {
      const mkt = (sectors.private || 0) + (sectors.black || 0);
      const stt = sectors.state || 0;
      if (mkt + stt > 0) mktPct = (mkt / (mkt + stt)) * 100;
    }

    const rv = (n) => (Number.isFinite(n) ? Math.round(n) : null);
    const socBits = [];
    if (Number.isFinite(p.socCons)) socBits.push(`Social Conservatism ${rv(p.socCons)}`);
    if (Number.isFinite(p.relig)) socBits.push(`Religiousness ${rv(p.relig)}/100 in percentile intensity`);

    let dec = null;
    const run0 = rivals[0];
    const rRow = run0 ? rowOf(run0.name) : null;
    if (wRow && rRow) {
      const dims = [
        { k: "the economic axis", v: x, ew: wRow[2], er: rRow[2], wt: 1 },
        { k: "the authority axis", v: y, ew: wRow[3], er: rRow[3], wt: 1 },
        { k: "traditionalism", v: trad, ew: wRow[4], er: rRow[4], wt: KT },
        { k: "radicality", v: radic, ew: wRow[5], er: rRow[5], wt: KR }
      ].filter((d) => d.v != null);
      let best = null;
      dims.forEach((d) => {
        const adv = (Math.abs(d.v - d.er) - Math.abs(d.v - d.ew)) * d.wt;
        if (adv > 0.5 && (!best || adv > best.adv)) best = { k: d.k, v: d.v, ew: d.ew, er: d.er, adv };
      });
      if (best) dec = { dim: best.k, v: best.v, ew: best.ew, er: best.er };
    }

    let gap = null;
    if (wRow) {
      const dims = [
        { k: "the economic axis", v: x, e: wRow[2] },
        { k: "the authority axis", v: y, e: wRow[3] },
        { k: "traditionalism", v: trad, e: wRow[4] },
        { k: "radicality", v: radic, e: wRow[5] }
      ].filter((d) => d.v != null).map((d) => ({ k: d.k, gap: Math.abs(d.v - d.e) }));
      dims.sort((a, b) => b.gap - a.gap);
      if (dims[0] && dims[0].gap > 15) gap = { dim: dims[0].k, v: dims[0].gap };
    }

    let corr = null;
    if (winner === mapLeader) {
      const r = prefsReason(winner.name, p);
      if (r) corr = r;
    }

    const facts = {
      x, y, civil: p.civil, pol: p.pol, govtSize: p.govtSize, econFree: p.econFree, econ,
      mktPct, socBits, trad, radic, tax: p.tax, welfareRank: p.welfareRank,
      cx: wRow ? wRow[2] : null, cy: wRow ? wRow[3] : null, tExp: wRow ? wRow[4] : null, rExp: wRow ? wRow[5] : null,
      dist: winner.d, dec, gap, corr
    };
    const desc = ideoExplanation(winner, vetoes, rivals, p, econWord, freeWord, govtSpending, policies, mapLeader, facts);
    return { family: winner.family, name: winner.name, desc };
  }
module.exports = { specificIdeology, compassPoint, IDEOLOGIES, sigPass, prefsScore };
